# Generated by Django 4.2.3 on 2023-08-24 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField()),
                ('degree_field', models.CharField()),
                ('degree_type', models.CharField()),
            ],
        ),
    ]
