# Generated by Django 4.2.3 on 2023-08-13 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField()),
                ('city', models.CharField()),
                ('state', models.CharField()),
                ('zip', models.BigIntegerField()),
            ],
        ),
    ]
