# Generated by Django 4.2.3 on 2023-08-24 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('education_app', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('skills_app', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='education_app.education')),
                ('email', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('skills', models.ManyToManyField(default=None, related_name='applicants', to='skills_app.skill')),
            ],
        ),
    ]
