# Generated by Django 4.2.3 on 2023-08-15 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applicant_app', '0003_remove_applicant_favorites'),
        ('company_app', '0002_rename_company_name_company_name'),
        ('recruiter_app', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiter',
            name='favorites',
            field=models.ManyToManyField(default=None, related_name='Recruiters', to='applicant_app.applicant'),
        ),
        migrations.AlterField(
            model_name='recruiter',
            name='company',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='company_app.company'),
        ),
    ]
