# Generated by Django 4.2.3 on 2023-08-13 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(unique=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='address_app.address')),
            ],
        ),
    ]
