# Generated by Django 4.2.3 on 2023-08-23 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address_app', '0001_initial'),
        ('company_app', '0002_rename_company_name_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='address_app.address'),
        ),
    ]
