# Generated by Django 4.2.3 on 2023-08-13 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job_Posting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
                ('job_type', models.CharField()),
                ('job_description', models.CharField()),
                ('salary_range', models.BigIntegerField()),
                ('location', models.CharField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_app.company')),
            ],
        ),
    ]
