# Generated by Django 4.2.3 on 2023-08-24 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recruiter_app', '__first__'),
        ('applicant_app', '__first__'),
        ('company_app', '__first__'),
        ('skills_app', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job_Posting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
                ('job_type', models.CharField(default='full-time')),
                ('job_description', models.CharField()),
                ('degree_type', models.CharField(default='none')),
                ('salary', models.BigIntegerField()),
                ('location', models.CharField()),
                ('applicants', models.ManyToManyField(default=None, related_name='favorites', to='applicant_app.applicant')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_app.company')),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiter_app.recruiter')),
                ('skill', models.ManyToManyField(default=None, related_name='job_postings', to='skills_app.skill')),
            ],
        ),
    ]
