# Generated by Django 4.2.3 on 2023-08-13 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('skills_app', '0001_initial'),
        ('job_posting_app', '0001_initial'),
        ('recruiter_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_posting',
            name='recruiter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiter_app.recruiter'),
        ),
        migrations.AddField(
            model_name='job_posting',
            name='skill',
            field=models.ManyToManyField(related_name='job_postings', to='skills_app.skill'),
        ),
    ]
