# Generated by Django 4.2.3 on 2023-08-15 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant_app', '0003_remove_applicant_favorites'),
        ('job_posting_app', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_posting',
            name='applicants',
            field=models.ManyToManyField(default=None, related_name='favorites', to='applicant_app.applicant'),
        ),
    ]
