# Generated by Django 4.2.3 on 2023-08-16 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_posting_app', '0003_job_posting_applicants'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job_posting',
            old_name='salary_range',
            new_name='salary',
        ),
        migrations.AddField(
            model_name='job_posting',
            name='degree_type',
            field=models.CharField(default='none'),
        ),
        migrations.AlterField(
            model_name='job_posting',
            name='job_type',
            field=models.CharField(default='full-time'),
        ),
    ]
